### ISSUE TITLE
clear memory before write

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/hbprotocol#14]
Check out bug: Requesting of statistical data 0x25 works only with ACK, not noACK. Could be a more general problem.
(from https://github.com/bipropellant/hbprotocol/pull/13)

**Comment by btsimonh** [comment]
just a note on write:
this code:
```
                    for (int j = 0; ((j < params[i].len) && (j < (msg->len-2))); j++){
                        *(dest++) = writevals->content[j];
                    }
```
means that you can write any number of bytes up to the structure size.
So write functions should set the written structure to 'defaults' in pre-write?
e.g. stats counters *could* be zeroed by pre-write.
```
        case FN_TYPE_PRE_WRITE:
            // ensure clear in case of short write
            memset(param->ptr, 0, param->len);
            break;
```

... but other structures *may* choose NOT to set values to defaults (because you may only want to overwrite the start....).
Implications: for things like stats, we can expand the stats structure without being concerned that the content would not be reset when we wrote it if the controller did not know about the enhanced structure.

**Comment by p-h-a-i-l** [comment]
I think we should handle that for each variable in the FN_TYPE_PRE_WRITE part, like you proposed. 
For commands which have NULL right now, we can use a general handler.

**Comment by p-h-a-i-l** [comment]
Fixed my inital problem, not a bug in hbprotocol but in my C++ wrapper. I'll leave the issue open for the memset suggestion..

**Comment by p-h-a-i-l** [comment]
also included in https://github.com/bipropellant/hbprotocol/pull/17
