### ISSUE TITLE
ACK / NACK handling

### ISSUE THREAD

**Issue by p-h-a-i-l** [bipropellant/hbprotocol#4]
I was thinking about our current message acks and nacks. Right now we send a message, wait for the ACK and afterwards send the next message. If there is no ACK, we try to resend.

For me, there are two motivations:
1. Measure Packet loss (improve connection, debug)
2. Improve robustness, automatic retry to send messages.

Our current way does not allow to poll and work on uart just once in the main. A backlog can only be reduced, when both sides talk to each other.
If messages are kept too long, the content might be outdated (e.g. if the buffer holds multiple SpeedData or Hall Messages, only the latest is of interest. Everything before is old news and could be deleted.)
Measuring packet loss could be achieved without ACK, just by looking at CI. If CIs are skipped, a package was lost. Of course, only the receiving end will know. Maybe a heartbeat would be helpful to have constant traffic?

**Comment by btsimonh** [comment]
What you describe is like the classic TCP vs UDP issue.
TCP gives reliability in content, but sometimes you have to wait.
UDP gives reliability in timing, but no built in data recovery.

You highlight the fact that we have different messaging requirements on the same link.

Two possible approaches:
1. We go with a different SOM, like VESC, one for ACKed messages, and one for un-acked.
2. We go with defined command ranges, ACKed and un-ACKed.

I like (1), because then we have the option of sending the same command in different ways without changes to the upper levels?  (but we may have to augment the receive function to tell us what kind of message it was - so maybe (2) is better.  Maybe we go with Upper case letter commands ACKed, lower case not - then the parsing routines just convert to lower case to understand the command regardless of send style?

Another thing is we currently don't formally implement something in the upper level that knows if a message  was received - i.e. we don't inform the original sender that the ack was received, or the message lost - I'm thinking this would mainly be on the controller side for which we don't have combined pattern code for yet anyway.  In JS, this would be a callback?

p.s. 'T' can be used as a heartbeat - but we should remove the current double return!  My current NodeRed flow sends 'T' every second....

**Comment by p-h-a-i-l** [comment]
I like the apporach with multiple SOMs. Uppercase and lowercase is very similar, but less clean.

Informing the upper side is still far away for me. For now I just want to have a responsive protocol and information about packet loss in general.

**Comment by btsimonh** [comment]
ok, unless we want to examine the ascii control codes for name suitability, I suggest 
2 = acked
3 = (reserved, in case we go for similar to VESC in message length)
4 = not acked.
5 = (reserved, in case we go for similar to VESC in message length)

Different CI stored for acked & not acked?  else CI handling will need too much thought.

**Comment by p-h-a-i-l** [comment]
Codes look good.

Whatever is simpler to implement for CI.

**Comment by btsimonh** [comment]
Can you outline an operational practice for this?
Would we say 'normally' certain messages would be without ACK?
Or would we implement a subscribe scheme ('subscribe 02'|'subscribe 03')?
Or has the need gone away now the acked protocol is working better :) ?

**Comment by p-h-a-i-l** [comment]
Imagine a burst disturbance, the bus is not available for some time. As soon as the bus is back online, the full Buffer is replayed before the latest messages are sent. 
Also we artificially limit ourselves to half-duplex communication this way.

**Comment by p-h-a-i-l** [comment]
will be handled in https://github.com/bipropellant/hbprotocol/pull/13
